all:
  project_dir: "/scr1/users/danielsg/ITS_PIPITS_BROCC"
  ncbi_db: "/mnt/isilon/microbiome/analysis/biodata/blast/nt_20180816/nt"
  mux_dir: "multiplexed_fastq"
  demux_dir: "demultiplexed_fastq"
  threads: 4
  ITS_subregion: ITS1 

demux:
    mismatch: 0
    revcomp: false
